apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: social
spec:
  replicas: 2
  selector: { matchLabels: { app: backend } }
  template:
    metadata:
      labels: { app: backend }
    spec:
      containers:
        - name: backend
          image: 123456789012.dkr.ecr.eu-central-1.amazonaws.com/social-backend:latest
          ports: [{ containerPort: 8080, name: http }]
          envFrom:
            - configMapRef: { name: backend-config }
            - secretRef:    { name: backend-secrets }   
          readinessProbe:
            httpGet: { path: /v1/health, port: http }
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /v1/health, port: http }
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests: { cpu: "200m", memory: "256Mi" }
            limits:   { cpu: "500m", memory: "512Mi" }
