apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: social
spec:
  replicas: 1
  selector: { matchLabels: { app: redis } }
  template:
    metadata: { labels: { app: redis } }
    spec:
      containers:
        - name: redis
          image: redis:6.2-alpine
          args: ["redis-server","--save","60","1","--loglevel","warning"]
          ports: [{ name: redis, containerPort: 6379 }]
          resources:
            requests: { cpu: "50m", memory: "64Mi" }
            limits:   { cpu: "200m", memory: "256Mi" }
