apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-secrets
  namespace: social
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-sm
    kind: ClusterSecretStore
  target:
    name: backend-secrets
    creationPolicy: Owner
  data:
    - secretKey: AUTH_TOKEN_SECRET
      remoteRef: { key: social/backend, property: AUTH_TOKEN_SECRET }
    - secretKey: AUTH_BASIC_PASS
      remoteRef: { key: social/backend, property: AUTH_BASIC_PASS }
    - secretKey: SENDGRID_API_KEY
      remoteRef: { key: social/backend, property: SENDGRID_API_KEY }
    - secretKey: MAILTRAP_API_KEY
      remoteRef: { key: social/backend, property: MAILTRAP_API_KEY }
    - secretKey: DB_URL
      remoteRef: { key: social/backend, property: DB_URL }
    - secretKey: FROM_EMAIL
      remoteRef: { key: social/backend, property: FROM_EMAIL }
    - secretKey: CORS_ALLOWED_ORIGIN
      remoteRef: { key: social/backend, property: CORS_ALLOWED_ORIGIN }
