apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-secrets
  namespace: social
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-sm
    kind: ClusterSecretStore
  target:
    name: db-secrets
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_DB
      remoteRef: { key: social/db, property: POSTGRES_DB }
    - secretKey: POSTGRES_USER
      remoteRef: { key: social/db, property: POSTGRES_USER }
    - secretKey: POSTGRES_PASSWORD
      remoteRef: { key: social/db, property: POSTGRES_PASSWORD }
