
    - name: Install prerequisites
      apt:
        name:
          - wget
          - apt-transport-https
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Add Trivy GPG key
      apt_key:
        url: https://aquasecurity.github.io/trivy-repo/deb/public.key
        state: present

    - name: Add Trivy repository
      apt_repository:
        repo: "deb https://aquasecurity.github.io/trivy-repo/deb {{ ansible_lsb.codename }} main"
        state: present
        filename: trivy

    - name: Update apt cache after adding Trivy repo
      apt:
        update_cache: yes

    - name: Install Trivy
      apt:
        name: trivy
        state: present
